### ISSUE TITLE
Default font mismatch

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#1028]
**Describe the bug**
There are 2 different fonts in the application (see screenshot).

**To Reproduce**
1. Open GUI

**Expected behavior**
The font in green and red boxes should be the same; preferably it should be the one from the green box.

**Screenshots**
![image](https://user-images.githubusercontent.com/11719673/81944890-5a0e2e80-95cb-11ea-9464-5aeb8e0a6766.png)

**CaPTk Version**
master

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by ashishsingh18** [comment]
Was this in release or debug mode?

**Comment by sarthakpati** [comment]
Both.

**Comment by ashishsingh18** [comment]
@AlexanderGetka-cbica Do you remember why we added the font change for "QWidget" from the preferences? Was it to handle a specific platform? This issue could be because of that.

**Comment by AlexanderGetka-cbica** [comment]
@ashishsingh18 as we discussed on the phone, I remember having a similar issue to this. The "QWidgets" part of the function makes it only apply to QWidgets throughout the GUI, not action menus, etc as shown in Sarthak's screenshot. You are right, removing that part of the function call makes everything uniform*.

I realized after our call that I may actually have done that **deliberately**, so that no matter what font was set, the Actions menus would still be readable so users could access the preferences. In hindsight, that doesn't really solve anything, as the preferences menu would be in the same (potentially unreadable) font anyway. Therefore, it may not be a problem to remove that part of the function call, because I don't think this was for a specific platform after all.

**However**, the other issue here is that the font circled in Red is apparently not uniform across machines. On the current CaPTk master, I don't get that font, even when removing my preference file.

If I remove the "QWidgets" part of the function call, I get this:
![image](https://user-images.githubusercontent.com/59709326/82011240-5cf83600-9642-11ea-9522-78e23b60b0bf.png)

Pretty sure pink is the intended font set by the style sheet. The light blue font is related to the dock widget issue (see footnote).

As it is now, if a user runs CaPTk fresh (no prefs file exists), I think an empty string is set as the qapp font. Then this gets saved during closing, which means even new versions of CaPTk would also read in the "empty string" font. If this font does differ across machines, then we probably need to add a mechanism that explicitly uses a fallback font in the event an empty string is loaded or if no prefs file exists. That should solve this without any major changes to the structure of the preferences classes.

* Except the dock widget title bar: "Double click to dock/undock". That is an issue where title bars are very finicky. Technically, we could set the titlebarwidget to be a QLabel or something, and then the app-wide font should apply as well. But that may lead to more trouble.

**Comment by ashishsingh18** [comment]
> 
> 
> @ashishsingh18 as we discussed on the phone, I remember having a similar issue to this. The "QWidgets" part of the function makes it only apply to QWidgets throughout the GUI, not action menus, etc as shown in Sarthak's screenshot. You are right, removing that part of the function call makes everything uniform [see footnote].
> 
> I realized after our call that I may actually have done that **deliberately**, so that no matter what font was set, the Actions menus would still be readable so users could access the preferences. In hindsight, that doesn't really solve anything, as the preferences menu would be in the same (potentially unreadable) font anyway. Therefore, it may not be a problem to remove that part of the function call, because I don't think this was for a specific platform after all.

 _This seems to be fixed now. @sarthakpati @AlexanderGetka-cbica Can you test it on your side from here(https://github.com/ashishsingh18/CaPTk/tree/Issue_1028)? How do we test this on other platforms?_

> 
> **However**, the other issue here is that the font circled in Red is apparently not uniform across machines. On the current CaPTk master, I don't get that font, even when removing my preference file.
> 
> If I remove the "QWidgets" part of the function call, I get this:
> ![image](https://user-images.githubusercontent.com/59709326/82011240-5cf83600-9642-11ea-9522-78e23b60b0bf.png)
> 
> Pink is the application-wide font from a fresh start. The light blue font is related to the dock widget issue (see footnote).
> 
> As it is now, if a user runs CaPTk fresh (no prefs file exists), I think an empty string is set as the qapp font (pink). 

_Empty string was not set as qapp font. However empty string was stored and this was a bug which has also been fixed here._

>Then this gets saved during closing, which means even new versions of CaPTk would also read in the "empty string" font. If this font does differ across machines, 

_Font will differ from machine to machine. Qt picks up the default system font which is dependent on the OS and locale._

>then we probably need to add a mechanism that explicitly uses a fallback font
in the event an empty string is loaded or if no prefs file exists. That should solve this without any major changes to the structure of the preferences classes.

_We should let Qt do the font management. Hopefully with the fix, this should be fine._ 

>     * Except the dock widget title bar: "Double click to dock/undock". That is an issue where title bars are very finicky. Technically, we could set the titlebarwidget to be a QLabel or something, and then the app-wide font should apply as well. But that may lead to more trouble.

_Dockwidget title is still an issue. Title bars are not handled by Qt, these are managed by the window manager. We need to think of a workaround here._

**Comment by sarthakpati** [comment]
> Font will differ from machine to machine. Qt picks up the default system font which is dependent on the OS and locale.

I think as long as we let Qt pick up the default OS font/settings, this is fine.
