### ISSUE TITLE
[Training Module][GUI] Application Crash when running training module

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#1066]
**Describe the bug**
CaPTK crashes when running training module.

**To Reproduce**
1. Open training module from Applications->Training Module
2. Provide input data from downloaded sample data as shown in screenshot
3. Select SVM Classification Kernel to RBF
4. Select Configuration to Cross Validation with # folds 3( or 2 or other number )
5. Provide output directory
6. Click Confirm - > Leads to application crash

**Expected behavior**
Application should produce results

**Screenshots**
![image](https://user-images.githubusercontent.com/43445206/83548301-913c7500-a4d1-11ea-8234-795cda16ffbd.png)

**CaPTk Version**: 1.8.0 Alpha

**Desktop (please complete the following information):**
 - OS: Win 10 Enterprise, x64

**Comment by AlexanderGetka-cbica** [comment]
I'm going to self-assign and look into this as well. Perhaps it is not algorithmic.
Or perhaps it is and I can maybe save Saima some time.

**Comment by ashishsingh18** [comment]
@AlexanderGetka-cbica Please let me Saima know via email that you are looking at this. Perhaps she already has a fix for this.

**Comment by AlexanderGetka-cbica** [comment]
After some digging I found the following.

This crash occurs (sooner, in debug) due to failing a CV_Assert condition in the predict() function of the SVM class provided by OpenCV:
` CV_Assert( samples.cols == var_count && samples.type() == CV_32F );`

In the calling TrainingModule.cpp code we have InternalCrossValidationResubstitution() which internally creates an SVM and later calls its "predict()" function as part of a loop to create predictions for each row of the training data (each sample). The sample is passed to predict(). var_count is a variable of the SVM itself, but at the time this statement is executed it seems uninitialized: 
  | Name | Value | Type
  | var_count | -842150451 | int

**Comment by AlexanderGetka-cbica** [comment]
With the "change 1 to 1.0" fix on line 2063 of TrainingModule.cpp, this now runs for me without crashing. But I don't know how to validate the results -- all I know is that this fix causes the SVM's "gamma" setting to be set to 0.500000 for RBF (instead of 0.0000000 which was causing the crash) and 1.0000000 for linear (which it was already doing). 
@saimarathore Do you have any input? Should both Linear and RBF kernels be using the same gamma (and if so, which value for it?)

**Comment by saimarathore** [comment]
Hi Alex, I have fixed this in my PR 1089.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
