### ISSUE TITLE
EGFRvIII Surrogate Index (PHI estimator) produces different results between GUI and CLI

### ISSUE THREAD

**Issue by AlexanderGetka-cbica** [CBICA/CaPTk#1073]
**Describe the bug**
Running the EGFRvIII surrogate index (PHI estimator) on the sample data, from the GUI, produces output that seems erroneous.
Specifically, I get PHI: 0, peak height ratio: nan, and 0 voxels used. 
When I run from the CLI, I get numeric output that seems (to my untrained eye) to be valid.

**To Reproduce**
1. Open CaPTk GUI.
2. Load DSC-MRI, T1-Gd and T2-FLAIR data from sample data using the Load-> Image menu.
3. Load the near and far ROI file, also in the sample data, using Load -> ROI menu. (note the mask is very small and hard to see but does appear to be present).
4. Run the Surrogate Index / PHI Estimator.
5. See screenshot.

**Expected behavior**
I expected to receive data that was numeric, if not necessarily correct. When I run from the CLI I receive a PHI greater than 0, a number for peak height ratio, and "voxels used" greater than 0.

**Screenshots**
![image](https://user-images.githubusercontent.com/59709326/83590853-b0b0bd80-a524-11ea-831f-42fb119b0869.png)

**CaPTk Version**
1.8.0.Alpha 

**Desktop (please complete the following information):**
Windows 7 Home x64

**Comment by saimarathore** [comment]
I just ran the EGFRvIIISurrogateIndex (PHI estimator) module using 1.8.0Alpha. I got PHI index=0.0714689 both from CLI and GUI using the sample data. Are you getting the same value from CLI? I am unable to replicate this issue. 
The module is picking all the 48 near and 47 far voxels in my case, but is not picking any voxel in your case. This happens when the standard deviation of voxels intensities across the time-points is very low. Did you apply any type of scaling or your image got chopped off after loading?

**Comment by AlexanderGetka-cbica** [comment]
I didn't apply any preprocessing to the images -- I ran them directly from the sample data folder.

I tried loading the DSC-MRI again to double check and it seems to be giving me a blank image. And when I closed it and loaded it again CaPTk crashed. I also noticed my memory use going up and up every time I did this...

Turns out after freeing up some resources, the perfusion image was much larger than I thought. But once I got it to load, the PHI estimator ran and I got the same result as you. 

It seems that this isn't really an issue with this application as much as it is with loading large images!
Thanks Saima. I'll close this and open a new issue.
