### ISSUE TITLE
Module failure: "Glioblastoma Survival Prediction Index"

### ISSUE THREAD

**Issue by anahitafk** [CBICA/CaPTk#1245]
**Describe the bug**
The module "Glioblastoma Survival Prediction Index" returns an error : "No patient inside the given input directory has required scans"

**To Reproduce**
1. Go to 'Applications'
2. Click on 'Glioblastoma Survival Prediction Index'
3. Click on "Use an existing survival prediction model", choose the directory for the downloaded UPenn model, Select the folder for Test Subjects, Choose the output folder, and click "Confirm"
4. See error: "No patient inside the given input directory has required scans"

**Expected behavior**
The data has been organized according to the guidelines of CaPTk; the expected behavior is a prediction of survival

**Screenshots**
![image](https://user-images.githubusercontent.com/45635727/90038981-0ecfee80-dc94-11ea-80c9-dd5c846e408d.png)
![Capture](https://user-images.githubusercontent.com/45635727/90063296-24a2db00-dcb7-11ea-8b74-ec92a6eadb4e.JPG)

**CaPTk Version**
Cancer Imaging Phenomics Toolkit (CaPTk) v.1.8.0.Beta

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10.0.17134 Build 17134

**Additional context**

**Comment by AlexanderGetka-cbica** [comment]
@anahitafk Thank you for the bug report. In order to help us resolve this issue, could you please provide a few additional details? Specifically, it would be helpful to know:

1. The directory/file structure of your input. On Windows, the easiest way to get this is to navigate to your Test Subjects input directory in the Command Prompt (or PowerShell) and enter the command  `tree /f . `. Please copy-and-paste the output (either here as a separate message or in a text file). Alternatively, if the data is fully anonymized, you may zip it up and send that.

2. Does the Survival Prediction Index work for you when using it with the provided sample data? The sample data should be accessible from Help -> Sample Data -> SurvivalPredictor. 

3. The location of the documentation you used to construct your input, so that we can correct it if needed.

**Comment by anahitafk** [comment]
Hi Alex,
Please find answers to your questions here:

1) The directory/file structure of your input. On Windows, the easiest way to get this is to navigate to your Test Subjects input directory in the Command Prompt (or PowerShell) and enter the command tree /f . . Please copy-and-paste the output (either here as a separate message or in a text file). Alternatively, if the data is fully anonymized, you may zip it up and send that.
[-](https://upenn.box.com/s/yhbe4wxzn61br4fl8auqnt1qnbu3orms)



2) Does the Survival Prediction Index work for you when using it with the provided sample data? The sample data should be accessible from Help -> Sample Data -> SurvivalPredictor.
- It doesn't work on the sample data either

3) The location of the documentation you used to construct your input, so that we can correct it if needed.
Help--> Usage--> How To Guides--> Specialized Applications (SAs) Usage--> Brain Cancer: Glioblastoma Survival Prediction Index

**Comment by AlexanderGetka-cbica** [comment]
Thank you for the quick response!

Could you please perform an additional test? Create a directory called "subjects" or similar, and copy one or more of the subject directories (AAAA_2007.01.21, AAAB_2006.10.28, etc...) into that "subjects" directory. Then call SurvivalPredictor.exe and pass the "subjects" directory as the input to `-i` instead of the individual subject.

**Comment by anahitafk** [comment]
Thanks Alex for your message. I tested it and it still doesn't work: with GUI, I get the same error and with CLI, it stops working as in the below figure, but in my opinion, if creating a "subjects" directory is necessary, it should have be explicitly mentioned in the guidelines. 

![image](https://user-images.githubusercontent.com/45635727/90068170-376cde00-dcbe-11ea-9f78-24906eae207b.png)

**Comment by saimarathore** [comment]
@AlexanderGetka-cbica Hi Alex, were you able to reproduce this bug? i ran from GUI and CLI using the sample data, and it worked fine for me.

**Comment by AlexanderGetka-cbica** [comment]
@saimarathore The first reported case in this issue appears to have been that survival didn't detect any subjects. When following the "samples/subject_name/modality.nii.gz" structure, the subject detection works for me from both CLI and GUI, but doesn't seem to work for Anahita on the GUI. 
The latter case shows a crash when running the algorithm after some subjects have been detected... I have had this happen when my machine is out of memory, but this is situational.

**Comment by saimarathore** [comment]
works fine on CLI and GUI.
