### ISSUE TITLE
problem with downloading sample data

### ISSUE THREAD

**Issue by anahitafk** [CBICA/CaPTk#1378]
**Describe the bug**
The sample data seems to have a broken link. By clicking on it, nothing starts to be downloaded

**To Reproduce**
1. Go to 'Help'
2. Click on 'Sample Data'
3. Scroll down to 'All'
4. Nothing happens

**Expected behavior**
A window for downloading the data should be opened

**Screenshots**

**CaPTk Version**
v.1.8.0.Beta

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10.0.17134

**Additional context**

**Comment by sarthakpati** [comment]
> v.1.8.0.Beta

Is it also seen in the stable version? I believe the "All" option has been removed because there were constant changes happening in per-application samples and it was getting harder to track.
![image](https://user-images.githubusercontent.com/11719673/101065533-432d2a80-3563-11eb-9370-275cfd80185f.png)

**Comment by anahitafk** [comment]
Thank you Sarthak. It works quite fine with the stable version.
