### ISSUE TITLE
Netlib routine lbfgs failed, Brain Mask was not written

### ISSUE THREAD

**Issue by camarasu** [CBICA/CaPTk#1487]
**Describe the bug**
When making command-line calls to the BraTSPipeline executable I get this error message, which prevents the brain mask completion:
```bash
mvnl_lbfgs: Error. Netlib routine lbfgs failed.
vnl_lbfgs: Error. Netlib routine lbfgs failed.
vnl_lbfgs: Error. Netlib routine lbfgs failed.
The version of model is incompatible with this version of CaPTk.
Brain Mask was not written, cannot proceed.
```

Please note that the first part of the pipeline executes correctly:
```bash
Executing with the default number of threads: 8
Number of NaNs: fixed: 0, moving 0
*************************************************
N=6 NUMBER OF CORRECTIONS=5 INITIAL VALUES F= -11076.5 GNORM= 33.9712
*************************************************
I NFN FUNC GNORM STEPLENGTH
1 2 -11106.069 30.352 0.029
[...]

Generating image for T2 registered to the atlas.
Greedy command: /work/CaPTk/bin/install/appdir/usr/bin/greedy -d 3 -a -m NMI -i sorina/T1CE_rai_n4.nii.gz sorina/T2_rai_n4.nii.gz -o sorina/T2_to_T1CE.mat -ia-image-centers -n 100x50x10 -dof 6
Starting skull-stripping using DeepMedic.
Command for DeepMedic: /work/CaPTk/bin/install/appdir/usr/bin/DeepMedic -md /work/CaPTk/bin/install/appdir/usr/bin/../data//deepMedic/saved_models/skullStripping/ -i sorina/T1_to_SRI.nii.gz,sorina/T1CE_to_SRI.nii.gz,sorina/T2_to_SRI.nii.gz,sorina/FL_to_SRI.nii.gz -o sorina/dmOut_skull/brainMask_SRI.nii.gz
```

**To Reproduce**
Build a Docker image using the Dockerfile (without its last line, concerning the GUI) and the current version of the software available in github.  
Command line example :
```bash
/work/CaPTk/bin/install/appdir/usr/bin/BraTSPipeline -t1c CDIN_AXI_T1_3D_GADO.nii.gz -t1 CDIN_SAG_T1_FFE.nii.gz -t2 CDIN_AXI_T2_3_5_mm.nii.gz -fl CDIN_AXI_FLAIR.nii.gz -o sorina
```

**CaPTk Version**
1.9.0.Alpha

**Desktop (please complete the following information):**
- Docker image build from provided Dockerfile (FROM cbica/captk_centos7:devtoolset-4_superbuild)

**Comment by AlexanderGetka-cbica** [comment]
Hi @camarasu, thanks for your interest in CaPTk. I'm looking into this. 
Normally, the netlib routine failure messages don't actually cause the process to fail ( for example, I see these when registering sometimes with the desktop version of the app, but it doesn't halt). 

The 1.9.0.Alpha had an issue wherein DeepMedic based models failed to run -- that also applied to skull stripping. So I think the error is occurring there. 

Since the 1.9.0.RC build is now committed to master, the repo Dockerfile should now pull those changes based on the latest commits and *should* fix this issue. Can you please try that?

If that doesn't work, please let me know and I'll investigate further.

**Comment by AlexanderGetka-cbica** [comment]
Great! 

Closing this issue. Feel free to open a new issue if any other difficulties arise.
