### ISSUE TITLE
MD5 checksum error running CaPTk_1.9.0_Installer.bin

### ISSUE THREAD

**Issue by waltman** [CBICA/CaPTk#1497]
**Describe the bug**
I'm getting an MD5 checksum error when I run the installer for CaPTk 1.9.0 for Linux.

**To Reproduce**
1. Go to https://www.nitrc.org/frs/?group_id=1059
2. Download the "Linux x64" binary for 1.9.0
3. In the Downloads directory, run `chmod +x CaPTk_1.9.0_Installer.bin`
4. Run `./CaPTk_1.9.0_Installer.bin`
5. Output is `Verifying archive integrity...  100%  Error in MD5 checksums: 9df41a32b9e541f8da0e73e47a114e94 is different from 671f843e156b5e455ced517e9df6ec07`

**Expected behavior**
I expected the installer to install version 1.9.0 of CaPTk

**Screenshots**
N/A

**CaPTk Version**
Version information is found on Help > About
1.9.0

**Desktop (please complete the following information):**
 - OS: Linux
 - Version (including Build information, if any): Ubuntu 20.04.4 LTS

**Additional context**

**Comment by AlexanderGetka-cbica** [comment]
Hi @waltman , thanks for reporting this. This happens due to corruption of the installer artifact. Sometimes these issues happen during download, but this happened for me too when I tried it just now. So I need to check where along the line this happened and re-upload. When I do, I'll close this. 

Thanks again!

**Comment by AlexanderGetka-cbica** [comment]
Closing this issue as I've re-uploaded the artifacts and it thankfully seems to work now. Please re-open if the issue persists.
