### ISSUE TITLE
Libra not working in CLI mode

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#313]
**Describe the bug**
Libra not working in CLI mode

**To Reproduce**
1. Run Libra as a command line as per the isntructions here(http://captk.projects.nitrc.org/BreastCancer_LIBRA.html) 
2. Getting a popup message that says "could not find 8.1 version of MCR" . Please see attached screenshot

**Expected behavior**
Libra should work and produce output as per documentation.

**Screenshots**
![image](https://user-images.githubusercontent.com/43445206/53823400-b2658d00-3f3f-11e9-84f8-9c4c12823b1b.png)

**CaPTk Version** 1.6.2

**Desktop (please complete the following information):**
 - OS: Windows 7 Enterprise SP1

**Comment by sarthakpati** [comment]
Documentation needs to be fixed. Instead of `Libra.exe`, it should be `libra.bat` for Windows and `libra` for Linux.

**Comment by ashishsingh18** [comment]
libra.bat also doesn't work. 
Says invalid input choice: --input

**Comment by sarthakpati** [comment]
Can you post the exact command you tried to use?

**Comment by pefs44** [comment]
I also have this problem with libra.exe - it gives error message about MCR 8.1 not being found and crashes. 
Using libra.bat as indicated by sarthakpati, the message box came up during the first run of libra, but the program continued to completion (in my case an error because I don't have a 2D mammo image to test with, but a couple of csv and sensible log file were generated). 
On running the libra.bat again the message box doesn't come up.

**Comment by sarthakpati** [comment]
I think there was some issue with the MCR in 1.6.2 and has been fixed in the new builds. Once the testing finishes, we will make the public links available for download.

**Comment by sarthakpati** [comment]
Closing
