### ISSUE TITLE
Can't load images on Windows 7 64bit

### ISSUE THREAD

**Issue by cb1544** [CBICA/CaPTk#400]
I'm trying to use CaPTk for a research project,
I installed the last version of CAPTk in windows (1.6.1) and every time I tried to load images it crashed. Same problem with the 1.6.2.Beta version.
Any idea why please ?

Thanks !
Camelia

**Comment by ashishsingh18** [comment]
Thanks for reporting this. Can you please give us more information about the crash? Any screenshots that you may have? What kind of data were you trying to load? The more information we get, the easier it is for us to replicate and solve the issue.

Thanks.

**Comment by cb1544** [comment]
I can't load anything  even the examples data available with CaPTK
I made a quick video that you can find [here ](https://drive.google.com/file/d/1RekulrTGXGrjm-97bKsP8HpSgJR2YQo0/view?usp=sharing)

Thanks!
Camelia

**Comment by sarthakpati** [comment]
Hey Camelia,

Could you please give us details about the hardware (CPU and GPU specifically), the display driver information being used (you can give us screenshots using the [dxdiag](https://www.cisco.com/c/en/us/td/docs/telepresence/endpoint/articles/cisco_telepresence_movi_find_out_graphics_card_driver_on_windows_pc_kb_540.html) tool). 

Thanks!

**Comment by cb1544** [comment]
Hi Sarthak,
Sure, here is it 
![dxdiag](https://user-images.githubusercontent.com/42389781/54628790-99cf9980-4a4c-11e9-93fc-1cb2fdd1887b.JPG)

Thanks !

**Comment by sarthakpati** [comment]
Related to issue raised by @dboun #404; keeping all conversation related to this in the same thread.

**Comment by sarthakpati** [comment]
Facing this issue on a particlar lab machine as well. Need to perform detailed diagnostics.

**Comment by dboun** [comment]
![dxdiag_system](https://user-images.githubusercontent.com/39439832/54648663-c8cb2700-4aaf-11e9-8277-a6e0030fb79f.png)
![dxdiag_display](https://user-images.githubusercontent.com/39439832/54648665-c8cb2700-4aaf-11e9-8077-2792a9f4a428.png)

Note that I have tried (not sure how successfully) to run CaPTk on both the integrated and the discreet gpu with no difference.

**Comment by sarthakpati** [comment]
> Facing this issue on a particular lab machine as well. Need to perform detailed diagnostics.

Here is the diagnostic information from that machine

![image](https://user-images.githubusercontent.com/11719673/54826551-6710e580-4c86-11e9-9c3d-2caf14609fbf.png)
![image](https://user-images.githubusercontent.com/11719673/54826566-6ed08a00-4c86-11e9-8c8f-8842d6ef937b.png)

**Comment by sarthakpati** [comment]
Some more diagnostics using the tool [GPU Caps Viewer](http://www.ozone3d.net/gpu_caps_viewer/) under the "quick OpenGL information" from the same "problematic" lab computer:

> GL_VENDOR: Intel
> GL_RENDERER: Intel(R) HD Graphics
> GL_VERSION: 3.1.0 - Build 8.15.10.2752
> GL_MAX_TEXTURE_SIZE: 8192
> GL_MAX_COLOR_ATTACHMENTS: 8
> GL_MAX_TEXTURE_IMAGE_UNITS: 16
> GL_MAX_TESS_GEN_LEVEL: 0

**My current hypothesis**: VTK 8.1 does not support anything below OpenGL 3.2 (which is shipped on Windows by default but needs to be enabled by the display hardware manufacturer in some cases) for rendering.

@dboun @cb1544 could you please give me similar information using that tool? Thanks.

**Comment by cb1544** [comment]
Hi @sarthakpati,

Here is mine : 
GL_VENDOR: ATI Technologies Inc.
GL_RENDERER: ATI Radeon HD 3450 - Dell Optiplex
GL_VERSION: 3.2.9210 Compatibility Profile/Debug Context
GL_MAX_TEXTURE_SIZE: 8192
GL_MAX_COLOR_ATTACHMENTS: 8
GL_MAX_TEXTURE_IMAGE_UNITS: 16
GL_MAX_TESS_GEN_LEVEL: 0

Thanks for taking care of this :)

Best,
Camelia

**Comment by sarthakpati** [comment]
> GL_VERSION: 3.2.9210 Compatibility Profile/Debug Context

Interesting...

**Comment by dboun** [comment]
```
GL_VENDOR: Intel
GL_RENDERER: Intel(R) HD Graphics 3000
GL_VERSION: 3.1.0 - Build 9.17.10.4459
GL_MAX_TEXTURE_SIZE: 8192
GL_MAX_COLOR_ATTACHMENTS: 8
GL_MAX_TEXTURE_IMAGE_UNITS: 16
GL_MAX_TESS_GEN_LEVEL: 0
```

Maybe it needs OpenGL 3.3?

**Comment by sarthakpati** [comment]
Whatever it may be, we need to be able to detect and throw a warning for it. I am testing something for this. I'll ask you both to test it, @cb1544 @dboun. It will come in this week's RC.

**Comment by ashishsingh18** [comment]
Can we try a simple 'Hello World' vtk example without Qt on this machine? That way we will know for sure if it is VTK/OpenGL issue or something else. I guess it will help narrow down the problem.

**Comment by dboun** [comment]
@ashishsingh18 can you provide a simple standalone? Because I'm not sure how functional is the VTK installation on my pc. Even if it is I have never used it so I don't know how to write code on it.

@sarthakpati Following the forum [here](https://community.citra-emu.org/t/force-opengl3-3-on-intel-hd-graphics-3000-windows/14122/56), I tried to deploy it with the perappdeploy.bat from [here](https://github.com/pal1000/mesa-dist-win/releases) and 'set MESA_GL_VERSION_OVERRIDE=3.3COMPAT' (and 3.2, 3.3) before I execute CaPTk with no difference. I even tried a different opengl32.dll as suggested in the thread but it didn't work.

---

Another useful resource is ["glewinfo.exe"](http://glew.sourceforge.net/index.html) (that you might already know). A mixture of mesa dlls from various sources [[dropbox link](https://www.dropbox.com/s/dxr93b7uzvwe0ih/dllsandglewinfo.zip?dl=0)] in the same directory actually worked on my pc with glewinfo.exe (but *not* with CaPTk).

-unzip and go inside folder
- set MESA_GL_VERSION_OVERRIDE=3.3COMPAT 
- glewinfo.exe -version 3.3 

glewinfo.exe will complain if it doesn't find some sort of opengl 3.3 and show nothing otherwise. With these dlls it didn't compain. Of course, on your machine it might find opengl 3.3 anyway. 

The fact that glewinfo worked with these dlls leads me to believe there might be something additional going on. Maybe some sort of hardware acceleration that can't be provided with the shared libraries?

**Comment by sarthakpati** [comment]
Let's see; I am packaging a new build with a small big of test code built-in to see if it works. Will keep everyone posted.

**Comment by ashishsingh18** [comment]
You may try any image viewing example from VTK examples list. 
https://lorensen.github.io/VTKExamples/site/Cxx/

**Comment by sarthakpati** [comment]
> You may try any image viewing example from VTK examples list.
> https://lorensen.github.io/VTKExamples/site/Cxx/

This is dependent on how VTK was built and will not reflect the environment of the current problem.

**Comment by sarthakpati** [comment]
For non-conformant OpenGL version, the following error comes up, now. 

![image](https://user-images.githubusercontent.com/11719673/54935000-d7716e00-4ef5-11e9-9fcb-28880d3f2851.png)

**Comment by sarthakpati** [comment]
Using the issue. Let's keep the thread open for discussion as needed. We will be testing a mechanism to lower the required OpenGL version on Windows but it unfortunately will not happen in this development cycle. 

Thanks for the feedback!
