### ISSUE TITLE
CaPTk 1.6.2 can't load images

### ISSUE THREAD

**Issue by dboun** [CBICA/CaPTk#404]
**Describe the bug**
CaPTk can't open images on my machine. 

- It crashes when trying I use Load>Images ( exactly like issue #400 ).
- It behaves like the two screenshots below if I drag and drop an image.

**To Reproduce**
1. Load an image into CaPTk either through load or drag n drop.

**Screenshots**
What happens after you drag and drop an image:
![Screenshot (1)](https://user-images.githubusercontent.com/39439832/54627854-ed59db80-4a7c-11e9-834a-3cef15abdf76.png)

What happens after you click on an image
![Screenshot (2)](https://user-images.githubusercontent.com/39439832/54627858-ed59db80-4a7c-11e9-99d9-25da24f7e7d8.png)

**CaPTk Version**
1.6.2

**Machine:**
 - OS: Windows 10 (1809)
 - Intel Core i7 2670QM
 - AMD Radeon HD 6490M (2012 midrange discrete laptop gpu)
 - Intel HD Graphics 3000 (integrated gpu)
 - 4GB RAM (😪)
 - 1366x768 resolution

**Additional context**
It is probably the gpu or the resolution? (My GPU drivers are updated). When I built from source some time ago I was getting issue when I run but I don't remember exactly what. It was something about vtk and opengl (and I also remember something about "glew" and "lights").

**Comment by sarthakpati** [comment]
Let's try and make sure that the issues are in the same place; otherwise it is hard to keep a track of the context. @dboun please post the results from what I asked from Camelia from [this post](https://github.com/CBICA/CaPTk/issues/400#issuecomment-474393544) in the thread of issue #400. Let's keep all conversations there. Closing this out.
