### ISSUE TITLE
Spaces in Path/File name not accepted by GreedyRegistration gui

### ISSUE THREAD

**Issue by pefs44** [CBICA/CaPTk#449]
**Describe the bug**
Selecting a file in the browser with a space in the name 

**To Reproduce**
place images in a folder with a space in the filename - e.g. C:/data/subj 1/images1.nii and C:/data/subj 1/image2

**Expected behavior**
Either successful handling of spaces in pathnames or a warning to remove spaces.

**Screenshots**
from log file: 2019:04:26,01:03:37;CaPTk;pefs4;C:/prog/CaPTk_Full/1.6.2/bin/GreedyRegistration.exe -reg -trf -a -f D:/data/pclin_glio/nii/glio32_1 - Copy/flair.nii.gz -i D:/data/pclin_glio/nii/glio32_1 - Copy/3dt1.nii.gz -t D:/data/pclin_glio/nii/glio32_1 - Copy/3dt1_reg_to_flair.mat -o D:/data/pclin_glio/nii/glio32_1 - Copy/3dt1_reg_to_flair.nii.gz -m NMI -n 100x50x5 -a

nothing happens.

**CaPTk Version**
1.6.2

**Desktop (please complete the following information):**
Windows 10, 

**Additional context**

**Comment by sarthakpati** [comment]
Unfortunately, spaces are not supported in CLI applications since it is not OS-agnostic (even detecting it is difficult - how to differentiate between a space in a path v/s space between 2 parameters?). If we manage to find a way to make this work in an OS-agnostic manner, we will include it in a future release.
