### ISSUE TITLE
Survival Predictor Testing is not working

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/CaPTk#699]
**Describe the bug**
The survival predictor testing using pre-trained model is not working.

**To Reproduce**
1. Put a sample dataset into a new folder (I used ```AAAE```)
2. Use this folder as the ```Test Subjects``` after clicking on 'Applications > Survival Predictor'
2. Click on 'Confirm'

**Expected behavior**
Valid output should get generated.

**CaPTk Version**
1.7.3.Beta

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10.1909

**Comment by saimarathore** [comment]
in fact, 4 other applications, including recurrence, molecular subtype, pseudo-progression, and egfrvIII index predictor are not working because of the same reason. 

The following function has been called in fMainWindow to check guess file names:
guessImageType(files[i]) == CAPTK::ImageModalityType::IMAGE_TYPE_AX)
This function assumes '_axial' in the filenames, whereas the sample data has 'axial'. 

The command-line-applications also have separate file checking mechanism. we might think about putting this function somewhere in utilities.

**Comment by sarthakpati** [comment]
> whereas the sample data has ```"axial"```

Actually, the filenames have ```"_axial_pp"``` for all the images that I have. When I load them on the front end, it automatically gets detected as "DTI_AX" (see screenshot for reference).

![image](https://user-images.githubusercontent.com/11719673/68996943-dd460600-086e-11ea-80b8-58926be8730d.png)

**Comment by sarthakpati** [comment]
Actually, for Survival, the sample image filenames are **axial.nii.gz** and for Molecular, they are **AX.nii.gz**.

**Comment by sarthakpati** [comment]
The fix for this has been added. It is critical that guessing filename should not be done based on arbitrary conventions in file naming and should be left on the user. Therefore, anything that needs the modality information should be taken from a CSV or list file where the user can specify which file belongs to which modality.

Tagging @ashishsingh18 @MarkBergman-cbica for possible future extension.

**Comment by sarthakpati** [comment]
Fixed using https://github.com/sarthakpati/CaPTk/commit/e17851d4fa05a96b97ab374f419a62bb1eaa6b32
