### ISSUE TITLE
sample data asks what app to open with

### ISSUE THREAD

**Issue by eac-upenn** [CBICA/CaPTk#718]
## Expected Behavior
  1. Choose item from Help>Sample Data menu
  2. It opens or downloads

## Actual Behavior

Windows(?) asks me what app to open the file with.

![image](https://user-images.githubusercontent.com/43213897/69967664-e24dbb00-14e6-11ea-8adc-d64c448ce0f3.png)

(Not sure why it's showing Opera as the default, Firefox is my default browser and I also have Chrome open . . . ?)

## Steps to Reproduce the Problem

  1. Choose any item from Help>Sample Data menu

## Specifications

CaPTk v.1.7.3 

OS Name	Microsoft Windows 10 Home
Version	10.0.18362 Build 18362

System Manufacturer	HP
System Model	HP Spectre x360 Convertible
System Type	x64-based PC

Processor	Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz, 2601 Mhz, 2 Core(s), 4 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. F.07, 14-Apr-16
SMBIOS Version	2.8
Embedded Controller Version	38.22
BIOS Mode	UEFI

**Comment by AlexanderGetka-cbica** [comment]
This feature normally opens up a browser window which then immediately initiates the download of the sample data.
In our case, we use the scheme "ftp" to initiate the download  (with a URL along the lines of "ftp://www.nitrc.org/home/groups/captk/downloads/SampleData_1.6.0/[current application].zip"). 

Unfortunately, without embedding a browser into CaPTk, we can only _request_ that the operating system open the provided URL.

By default, operating systems associate a few schemes/protocols (such as http with whatever the default browser is). Your Windows installation may have associated the http protocol with Firefox, but not necessarily the ftp protocol -- this would allow you, for example, to have a separate FTP client acting as a download manager separate from whatever browser you use. Keeping those two schemes disentangled would (arguably) be desirable behavior.
Your screenshot indicates that Opera is currently the selected application for FTP scheme. I'm not sure how Firefox and Opera handle their scheme association during installation, but they seem to be at least partially conflicting in your case.

Since we don't have any way to really control this and the user gets a choice, I am going to close this.
However, if this proves to be more common, we should add some informational text to tell the user that the external link will be opened in their browser.

**Comment by eac-upenn** [comment]
Thanks for this really informative explanation! (And I chose Opera for FTP — who knew.)

— Eric.

Eric A. Cohen   |   Eric.Cohen@pennmedicine.upenn.edu
Data Analyst
Computational Breast Imaging Group
University of Pennsylvania
