### ISSUE TITLE
susan denoise changes physical dimensions of some images

### ISSUE THREAD

**Issue by eac-upenn** [CBICA/CaPTk#757]
## Actual Behavior

Open the file. Choose `Preprocessing` > `Denoise-SUSAN`. Denoising completes without error, but Captk reports that the resulting denoised file has different physical dimensions than the source file.

![image](https://user-images.githubusercontent.com/43213897/70730299-ba263f00-1cd2-11ea-8da8-390a1b8c29a4.png)

In every case, Captk reports the same Image size and Spacing for the source and denoised files.

## Which files?

Most files don't have this problem. Of the ones I've tested, these do:

  1. All the files in the `LungCancer` sample data (both the "ct2pet" and "suv" file types).

  1. A walnut: `http://www.informatik.uni-leipzig.de/~wiebel/public_data/index.html` `walnut.nii.gz`

## Specifications
 
  - CaPTk v.1.7.3
  - Windows 7 Enterprise
  - SP 1
  - 64-bit
  - Intel Core 15-4570
  - 20GB RAM

**Comment by AlexanderGetka-cbica** [comment]
I have investigated this a while and found that the denoising function itself does not actually change the dimensions of the image. Rather, CaPTk throws this error because a mismatch in the image origins between the loaded images -- in the case of the walnut, the original image has origin (0, 0, 0). As far as I can tell, the image of the denoised walnut that gets saved is also of origin (0, 0, 0). 

However, when the denoised walnut is loaded in, CaPTk reads it with some kind of orientation fix that changes the origin to (-399, -295, 0). `ReadImageWithOrientFix` causes this. (I actually found a  [thread](https://discourse.itk.org/t/orientimagefilter-changes-the-origin-of-the-image/2200) from @sarthakpati mentioning this... 

Anyway, the "original" origin and direction are stored at load time in the `mSlicerManagers` but don't seem to be used -- and CaPTk then throws an error when you try to load the other image which it sees as incompatible.

I still need to do additional digging to find out why this is actually done and how to fix it, but this is what I know so far.

**Comment by sarthakpati** [comment]
@AlexanderGetka-cbica: you might want to use the ```Preprocessing -ss``` CLI to see if the output is actually in the same space or not.

**Comment by sarthakpati** [comment]
Is this fixed, @AlexanderGetka-cbica?

**Comment by AlexanderGetka-cbica** [comment]
I never solved this, unfortunately.

**Comment by sarthakpati** [comment]
Cannot replicate on Alpha. Guess it is fixed.
