### ISSUE TITLE
Rebuild/Repackage Theia to eliminate Pyinstaller vulnerability

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#845]
Rebuild/Repackage Theia to eliminate Pyinstaller vulnerability

**Comment by AlexanderGetka-cbica** [comment]
@sarthakpati Were you really able to get Theia working with PyInstaller on windows? I can build it successfully using PyInstaller on Linux, but it doesn't actually run correctly for me. I suspect this has to do with how it handles calling the other included python scripts, but I'm not sure. 

Do you know how the other files can be bundled into it? If not I have to do some more digging tomorrow.

**Comment by sarthakpati** [comment]
That is the version that is out there right now. I believe it was @PhucNgo1711 that did it, however. 

I am not 100% sure what the requirements for Theia are, to be honest. Again, @PhucNgo1711 is the correct person to ask since he was one of the original developers of the project. :)

**Comment by AlexanderGetka-cbica** [comment]
After getting some really weird behavior* trying to run Theia (either from the python script or from the onefile executable) on Linux, I talked with @PhucNgo1711 -- it appears that Theia wasn't tested / never worked on Linux.

@CBICA/devteam In order to prevent the vulnerability we would need someone with a windows machine to give Theia a quick onefile build and test.

* Seems to do nothing except change my cursor to a + (leaving me unable to interact normally with other applications). Then, if I click, I get import errors. Finally, after clicking three times, the program exits with a syntax error.

**Comment by MarkBergman-cbica** [comment]
Required for 1.8.0 release

**Comment by AlexanderGetka-cbica** [comment]
This is done now and working on Windows.

**Comment by ashishsingh18** [comment]
@AlexanderGetka-cbica Is this done for Linux and macOS too?

**Comment by AlexanderGetka-cbica** [comment]
The vulnerability only existed on Windows, so no need for a re-package of Theia on the other platforms.

However, before full release, the new binaries still need to put into the master repo.

**Comment by sarthakpati** [comment]
Closing.
