### ISSUE TITLE
Rebuild/Repackage Confetti to eliminate Pyinstaller vulnerability

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk#846]
Rebuild/Repackage Confetti to eliminate Pyinstaller vulnerability

**Comment by AlexanderGetka-cbica** [comment]
@dboun and I were able to get Confetti running in a packaged form using Nuitka. It does not produce a one-file executable, but rather a single folder that contains all the needed shared object files as well as the executable. (You also need to build the C++ component of Confetti using CMake and place those compiled shared objects in the same directory). 

From what I understand, Confetti was a problem here due to it being created using Python 2.7 -- I believe @sarthakpati has notes regarding DeepMedic.

**Comment by dboun** [comment]
Updates/notes:

Alex and I got Confetti python+nuitka running on windows after a lot of pain (not related to nuitka, mostly coming from the dependencies being very old). We documented the process we used for future reference, it will added to confetti's src directory.

( @AlexanderGetka-cbica about ConfettiCore.dll: it gets built - I presume statically - when you build captk. So we can just use that, no need to build it statically ourselves! )

**Comment by MarkBergman-cbica** [comment]
Required for 1.8.0 release

**Comment by PhucNgo1711** [comment]
@AlexanderGetka-cbica is the current Confetti on Windows the one that you packaged using Nuitka, or still the one from pyInstaller.

**Comment by AlexanderGetka-cbica** [comment]
I don't think the current Confetti executable was changed. I guess the executable we built must still be on Ashish's work laptop that Dimitri and I used. I do have the notes we kept of the process for Confetti in particular:
[confetti_nuitka_notes.txt](https://github.com/CBICA/CaPTk/files/4822983/confetti_nuitka_notes.txt)

**Comment by AlexanderGetka-cbica** [comment]
As Dimitri noted we had a lot of weird trouble getting this working on Windows but our process did work as written. Please also see his note about CaPTk building ConfettiCore.dll. 

@PhucNgo1711 If you run into any trouble at all with this please let me know. Since we only need to do this once, it makes sense to prioritize this.

**Comment by AlexanderGetka-cbica** [comment]
So I've been looking into this using nuitka as described above. 

The first time Dimitri and I did this we didn't notice that it fails to load the confetticore dll properly.
So now I'm in the midst of trying to get it to do this. The problem is that nuitka takes a different approach than PyInstaller did  to handling the python environment (like the way they set up magic variables like __file__ and so on), so some of the checks in ConfettiCore.py, which is basically an API for the DLL, don't work with nuitka. I'm working on a small patch to ConfettiCore.py that fixes this but it is proving to be agonizing.

**Comment by AlexanderGetka-cbica** [comment]
This works now and is ready to be added whenever it's time to finalize 1.8.0.

Fiddling with direct windows kernel calls through python and worrying about text encoding was a _ton of fun_

**Comment by sarthakpati** [comment]
> This works now and is ready to be added whenever it's time to finalize 1.8.0.
> 
> Fiddling with direct windows kernel calls through python and worrying about text encoding was a _ton of fun_

Yeah, Python is _awesome_ that way. 🤷 Let's coordinate this with @PhucNgo1711 #1043

**Comment by ashishsingh18** [comment]
@AlexanderGetka-cbica is this done?

**Comment by AlexanderGetka-cbica** [comment]
Yep, this is done. Just waiting to integrate the binaries into the master before release. Might need help with that, since Confetti is now multiple files rather than just the single-file executable.

**Comment by sarthakpati** [comment]
Closing.
