### ISSUE TITLE
Not able to visualize .nii files

### ISSUE THREAD

**Issue by DushyantSahoo** [CBICA/CaPTk#849]
**Describe the bug**
I am using ubuntu 18.04 and GUI. When I try to open .nii files, there is no visualization of the data. I have set of dicom files which I converted to .nii files using CaPTk and dcm2niix.

**To Reproduce**
Use some dicom files and convert them to .nii files. Go to files and load the .nii file.

**Expected behavior**
CaPTk should be able to visualize the images

**CaPTk Version**
1.7.6

**Desktop (please complete the following information):**
 - OS:Ubuntu
 - Version (including Build information, if any): 18.04

**Comment by AlexanderGetka-cbica** [comment]
@DushyantSahoo I can't seem to reproduce this from my initial tests. In order to help us investigate this issue more deeply, please give us more detailed steps to reproduce the problem.

Are you using the DICOM to NIFTI tool from CaPTk's GUI under preprocessing, or are you running the files through dcm2niix on the command line first, and then opening the resulting files in the CaPTk GUI? If the latter, please provide the exact command(s) you used.

Does this happen on every file you have tried, or only on some files? If you convert the files using a different method, can you visualize them?

**Comment by dboun** [comment]
There shouldn't be any issue with visualization of nii files. They are read by itk just like nii.gz do, and are loaded as itk::Image objects.

The issue is either:
- OpenGL. In that case you wouldn't be able to visualize anything. That happens when the GPU is "old". This can be verified by running ```glxinfo | grep "OpenGL version"```. If the version is smaller than 3.3 (or 3.2?) there are issues that nobody can really do anything about
- or (more probably) dicom -> nifti conversion. If that's the case, then sharing of data (on the cluster) that cause the issues will help the devs working on this potentially solve this.

**Comment by DushyantSahoo** [comment]
The issue was with OpenGL, just corrected and everything works fine now. It would be really helpful if there can be pop up saying that OpenGL is incompatible if it is smaller than 3.3
