### ISSUE TITLE
[Bug] Azure Linux Artifact doesn't work

### ISSUE THREAD

**Issue by dboun** [CBICA/CaPTk#853]
**Describe the bug**
```bash
dimitris@dimitris-lab:~/Downloads/CBICA.CaPTk_installer_Linux$ ./CaPTk_1.7.7.nonRelease.20200213.9015c6ad_Installer.bin --target /home/dimitris/Documents/Programs/CaPTk-1.7.7-nonRelease/
Creating directory /home/dimitris/Documents/Programs/CaPTk-1.7.7-nonRelease/
Verifying archive integrity...  100%  Error in MD5 checksums: e75069c2eaf8f420b42d89b1d6576579 is different from e5ad9157832be49398aaa28f56e35c19
```

(I downloaded and tried the artifact twice to be sure)

**To Reproduce**
1. Download linux artifact from PR #842 

**CaPTk Version**
1.7.7-nonRelease

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.3

**Additional Context:**
@sarthakpati Might be related to the cache or itk-snap changes that were recently made?

**Comment by sarthakpati** [comment]
This is definitely a space issue because before the packaging begins on Xenial, the usage is at 98% [[ref](https://dev.azure.com/CBICA/CaPTk/_build/results?buildId=1069&view=logs&j=82538e74-49f1-5405-62cc-28b0e28fe542&t=b378233a-7da2-5766-c9c5-70d5eaed4c06)]. Unsure why this doesn't simply complain about it rather than create a faulty installer, though.

Same issue is present on the Windows side as well...

Another reason for to move to self-hosting, I guess...

Paging @PhucNgo1711.

**Comment by sarthakpati** [comment]
This no longer seems to be an issue.
