### ISSUE TITLE
Deepmedic on cluster gives error

### ISSUE THREAD

**Issue by parthsharma853** [CBICA/CaPTk#879]
**Describe the bug**
Runnning the Deepmedic Segmentation with Pre-trained SkullStripping model on the cluster provides directory not found error on multiple login sessions. 

**To Reproduce**

>Command found at https://cbica.github.io/CaPTk/seg_DL.html
captk Deepmedic -t1 t1_LPS_rSRI.nii.gz -t1c t1ce_LPS_rSRI.nii.gz -t2  t2_LPS_rSRI.nii.gz -fl flair_LPS_rSRI.nii.gz -o output_dir -md deepMedic/saved_models/skullStripping

error

>=== Starting P1P2Normalize.
=== Done.
=== Starting resampling of images to isotropic resolution.
=== Done.
Starting DeepMedic Segmentation.
Running the following command:
/gpfs/fs001/cbica/software/lab/captk/centos7/1.7.6/bin/DeepMedic/gpfs/fs001/cbica/home/deepMedicRun -t1 LPS_rSRI_maskFinal.nii.gz/t1_normalized.nii.gz -t1c LPS_rSRI_maskFinal.nii.gz/t1ce_normalized.nii.gz -t2 rSRI_maskFinal.nii.gz/t2_normalized.nii.gz -fl rSRI_maskFinal.nii.gz/fl_normalized.nii.gz -model /cbica/software/lab/captk/centos7/1.7.6/data/deepMedic/saved_models/skullStripping/modelConfig.txt -load /cbica/software/lab/captk/centos7/1.7.6/data/deepMedic/saved_models/skullStripping/model.ckpt -test /cbica/home/patis/projects/CaPTk_master/data/deepMedic/configFiles/testApiConfig.txt -o ../../3_MASK/ACSL/ACSL_2019.02.28_LPS_rSRI_maskFinal.nii.gz
sh: /gpfs/fs001/cbica/software/lab/captk/centos7/1.7.6/bin/DeepMedic/gpfs/fs001/cbica/home/deepMedicRun: Not a directory
DeepMedic exited with code !=0.

**CaPTk Version**
1.7.6

**Desktop (please complete the following information):**
Linux on cluster

**Comment by sarthakpati** [comment]
Same as ticket 1354 on the RT system. Paging @chiharusako and @MarkBergman-cbica

**Comment by MarkBergman-cbica** [comment]
The error message is accurate:
`/gpfs/fs001/cbica/software/lab/captk/centos7/1.7.6/bin/DeepMedic/gpfs/fs001/cbica/home/deepMedicRun`
is not a directory. 
Breaking it down:
`/gpfs/fs001/cbica/software/lab/captk/centos7/1.7.6/bin/DeepMedic`
is valid and accurate. The next part of the _path_:
`/gpfs/fs001/cbica/home/deepMedicRun`
is inaccurate -- there is no home directory named "deepMedicRun".

Something in the CaPTk code is duplicating (appending?) path fragments.

I suspect the problem is related to incorrectly turning symlinks into absolute paths

What code is generating that path?

**Comment by MarkBergman-cbica** [comment]
Since the demonstration of this is cluster-specific, please follow up on RT.

**Comment by sarthakpati** [comment]
#886 should fix this... It will become available on ```~/testing/captkMyForkInstall/bin/``` for testing shortly.
