### ISSUE TITLE
Diffusion Derivative doesn't produce any output [Command Line] 

### ISSUE THREAD

**Issue by parthsharma853** [CBICA/CaPTk#909]
**Describe the bug**
Executing DiffusionDerivatives doesn't produce any output in the output directory when run on command line.

**To Reproduce**

Go to /cbica/home/sharmapa/comp_space/Testathon/nifti/ACSL

Command:
> captk DiffusionDerivatives -i ACSL_2019.02.28_dti.nii.gz -m ACSL_2019.02.28_dti_0000_mask.nii.gz -b ACSL_2019.02.28_dti.bval -v ACSL_2019.02.28_dti.bvec -a 1 -f 1 -r 1 -t 1 -o ../../7_Diffusion_Derivatives/ACSL

Output:

>Executable Name: DiffusionDerivatives
        Version: 1.7.6

>==========================================================================
Contact: software@cbica.upenn.edu

>Copyright (c) 2020 University of Pennsylvania. All rights reserved.
See COPYING file or https://www.med.upenn.edu/sbia/software-agreement.html
==========================================================================

There is no output generated in the output folder.

**CaPTk Version**
1.7.6

**Desktop (please complete the following information):**
Linux on cluster

**Comment by AlexanderGetka-cbica** [comment]
This seems to be a combination documentation and command line parsing issue.
From the usage for DiffusionDerivatives.exe:

> [  -v, --version]                         Prints information about software version 

This is very standard in our applications (passing -v ignores the other input, performs no operation and instead displays the version text. 
However, the documentation states (and as far as I know, this is true) that DiffusionDerivatives requires a bvec file provided _using the -v parameter_. The usage text for this application also says this.
This makes the application unusable from the command line, since it cannot accept a bvec file without canceling and printing version and it cannot run without accepting a bvec file.

If you try to run the command without the -v parameter passed, like:

> captk DiffusionDerivatives -i ACSL_2019.02.28_dti.nii.gz -m ACSL_2019.02.28_dti_0000_mask.nii.gz -b ACSL_2019.02.28_dti.bval -a 1 -f 1 -r 1 -t 1 -o /cbica/home/getkaa/deletethis/dd_out

OR if you pass the bvec file in using the (assumed) longword --Bvec (since the corresponding longword for the bval parameter is --Bval), like so:

> captk DiffusionDerivatives -i ACSL_2019.02.28_dti.nii.gz -m ACSL_2019.02.28_dti_0000_mask.nii.gz -b ACSL_2019.02.28_dti.bval --Bvec ACSL_2019.02.28_dti.bvec -a 1 -f 1 -r 1 -t 1 -o /cbica/home/getkaa/deletethis/dd_out

Then you get an error that makes even less sense, especially to end-users when comparing to the usage menu:

> The data type of the requested parameter, 'a' is classified as 'STRING' and cannot be returned as a BOOL.

The usage menu states that 1 = YES, 0 = NO for the -a -f -r- t parameters (and that each defaults to 1).
But if you remove -a, it says that it is a required parameter that is missing.

@CBICA/devteam From what I can tell, the -v parameter _in `DiffusionDerivatives.cxx`_ is associated properly, so I thought it must get intercepted by the `CaPTk.cxx` parameter handling, but there's nothing about it in there. Any ideas on where the (initial reported) error may be happening?

**Comment by sarthakpati** [comment]
> -v parameter in DiffusionDerivatives.cxx is associated properly

Actually, this is a bug in that file. No CLI should be using the following parameters since they are defined by ```CmdParser``` internally and will *always* be overridden: ```u, usage```, ```h, help```, ```v, version```, ```-u, --usage```, ```rt, run-test```, ```cwl, cwl```. 

I believe this is documented in the class definition as well.

**Comment by AlexanderGetka-cbica** [comment]
I fixed the issue here on my branch by changing the relevant parameter shortword and subsequent logic. However this uncovered another issue: using the sample data for Diffusion Derivatives I get an error message stating (repeatedly): "multiple bvalues not allowed" and finally an exception-caused crash from an ITK filter running presumably with no input:

> terminate called after throwing an instance of 'itk::ExceptionObject'
  what():  /home/agetka/work/CaPTk-superbuild-try2/debug/ITK-source/Modules/Filtering/DiffusionTensorImage/include/itkDiffusionTensor3DReconstructionImageFilter.hxx:668:
itk::ERROR: DiffusionTensor3DReconstructionImageFilter(0x5631b4405060): Number of baseline images is null

@saimarathore is looking into this -- apparently it worked before. Given the imminent circumstances I will need to ask about what exactly is happening in the diffusion derivatives code and why. 

The GUI usage of this seems to work perfectly fine, however -- another case where I may need some help determining which implementation is "correct".
