### ISSUE TITLE
CaPTk feature extraction fails because of resampling

### ISSUE THREAD

**Issue by omaghsoudi** [CBICA/CaPTk#953]
If you provide image and mask with the same image resolution, but different resampling number, the CaPTk feature extraction module fails to extract features.

I have resolved this issue with a pre-processing step for myself but CaPTk can resolve such an issue and print that the issue existed and has been resolved; instead of crashing.

**Comment by sarthakpati** [comment]
This is a philosophical question. I am generally of the opinion that if users want to process 2 images together, they need to be the same physical space (i.e., origin, voxel resolution, image size, direction, should all be the same [[ref](https://github.com/CBICA/CaPTk/blob/master/src/cbica_toolkit/src/cbicaITKUtilities.h#L373)]) because if a software starts automatically "aligning" 2 random images, it won't do anyone any good. 

Going back to one of the issues you posted, this firmly goes in the category of "being **this** tall, i.e., having basic understanding of data and how images work, to work the software. Happy to have a conversation via Skype/whatever with potential extension opportunities.

**Comment by omaghsoudi** [comment]
I agree and it makes sense.
